########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = ["${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml"]

# Repository Name
name = "IsaacSimZED"

[repo_build]
post_build.commands = []
licensing.enabled = false
fetch.pip.licensing_enabled = false

[repo_build.docker]
enabled = false

[repo_build.msbuild]
link_host_toolchain = true
vs_version = "vs2019" # Empty string will match all years and prioritize the newest, specifying vs2019 because of issue with usd libs and vs2022
"token:in_ci==true".vs_version = "vs2019"
"token:in_ci==true".vs_path = "C:\\vs2019"

[repo_precache_exts]
registries = [
    { name = "kit/default", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/107/shared" },
    { name = "kit/sdk", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/sdk/${kit_version_short}/${kit_git_hash}" },
]

ext_folders = [
  "${root}/exts"
]

[repo_symstore]
enabled = false
